// <auto-generated />
using System;
using Lemmikloomad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lemmikloomad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251211152715_addedKliinik")]
    partial class addedKliinik
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lemmikloomad.Models.Kliinik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kliinikud");
                });

            modelBuilder.Entity("Lemmikloomad.Models.Lemmikloom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Kaal")
                        .HasColumnType("float");

                    b.Property<int>("KliinikId")
                        .HasColumnType("int");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OmanikId")
                        .HasColumnType("int");

                    b.Property<string>("Procedure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KliinikId");

                    b.HasIndex("OmanikId");

                    b.ToTable("Lemmikloomad");
                });

            modelBuilder.Entity("Lemmikloomad.Models.Omanik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perekonnanimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sugu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Omanikud");
                });

            modelBuilder.Entity("Lemmikloomad.Models.Lemmikloom", b =>
                {
                    b.HasOne("Lemmikloomad.Models.Kliinik", "Kliinik")
                        .WithMany("Lemmikloomad")
                        .HasForeignKey("KliinikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lemmikloomad.Models.Omanik", "Omanik")
                        .WithMany("Lemmikloomad")
                        .HasForeignKey("OmanikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kliinik");

                    b.Navigation("Omanik");
                });

            modelBuilder.Entity("Lemmikloomad.Models.Kliinik", b =>
                {
                    b.Navigation("Lemmikloomad");
                });

            modelBuilder.Entity("Lemmikloomad.Models.Omanik", b =>
                {
                    b.Navigation("Lemmikloomad");
                });
#pragma warning restore 612, 618
        }
    }
}
